spring.datasource.url=jdbc:postgresql://ep-square-flower-api4n07w-pooler.c-7.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_FoDNJe0qRZM7&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_FoDNJe0qRZM7
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jackson.property-naming-strategy=LOWER_CAMEL_CASE
server.address=0.0.0.0
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ui22cs67@iiitsurat.ac.in
spring.mail.password=oblb qlen cdxz ubgx

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com