spring.datasource.url=jdbc:postgresql://localhost:5432/freelance_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jackson.property-naming-strategy=LOWER_CAMEL_CASE
server.address=0.0.0.0
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ui22cs67@iiitsurat.ac.in
spring.mail.password=oblb qlen cdxz ubgx

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true