spring.datasource.url=jdbc:postgresql://ep-square-flower-api4n07w-pooler.c-7.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_FoDNJe0qRZM7&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_FoDNJe0qRZM7
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jackson.property-naming-strategy=LOWER_CAMEL_CASE
server.address=0.0.0.0
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=483daa6c387a2d
spring.mail.password=3fef903d46026a

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true